### ISSUE TITLE
get code out of svn

### ISSUE THREAD

**Issue by dsschult** [icecube/skymap_scanner#1]
Make sure there is only one skymap scanner, and it's in github!

**Comment by blaufuss** [comment]
Triage:  https://code.icecube.wisc.edu/projects/icecube/changeset?reponame=IceCube&old=185122%40[…]ap_scanner&new=161979%40sandbox%2Fckopper%2Fskymap_scanner

**Comment by blaufuss** [comment]
![image](https://user-images.githubusercontent.com/4948847/144470089-687d7ee3-2ba8-47e0-8946-adefb2f299a1.png)

**Comment by blinkdog** [comment]
![master-yoda-always-two-there-are](https://user-images.githubusercontent.com/1283521/144470441-f8996106-45e7-484e-aeed-c53cfaa72ac1.gif)

**Comment by blaufuss** [comment]
Code is out of SVN and now here.   Older contents of this project, which drove "cloud operations" are now in a subdirectory called "cloud_tools".  The core skymap_scanner project is now here.
