### ISSUE TITLE
Clean up of symlinks

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#13]
Several files in `resources/scripts` are symlinks to `python`. This likely requires a cleanup.

**Comment by ric-evans** [comment]
This is similar (but different) to https://github.com/icecube/skymap_scanner/issues/5

**Comment by mlincett** [comment]
I have started a review / cleanup of the code but I@ric-evans is this issue blocking for you in some way?

**Comment by dsschult** [comment]
Something to keep in mind is whether this is an "icetray" project, or a regular python project.  They have different formats, with what @ric-evans is proposing is the python project format.

**Comment by ric-evans** [comment]
> Something to keep in mind is whether this is an "icetray" project, or a regular python project. They have different formats, with what @ric-evans is proposing is the python project format.

That's true. There's a large similarity in either format: let's reduce the number of directories with python files.
