### ISSUE TITLE
Additional I3 resources for millipede_wilks in `client_starter.py`

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#135]
Quoting a note from @tianluyuan in the current README:
> You may also need to add this line to the condor submit file if running millipede_wilks as some resources have been removed from the image.
> ```environment = "I3_DATA=/cvmfs/icecube.opensciencegrid.org/data I3_TESTDATA=/cvmfs/icecube.opensciencegrid.org/data/i3-test-data-svn/trunk"```

I understand this is required to access additional spline tables used in `millipede_wilks`.

Supporting this requires adapting the client launcher script in order to include the necessary Condor requirement.

Do we prefer mounting CVFMS or allowing for a larger image size in order to include all the required photon tables? I guess this will depend on the size of the additional files to be included, right?

**Comment by briedel** [comment]
For running on the grid we should assume that we have cvmfs. I am working on a standalone image right now. I think we are looking at ~5-6 GB for that image. I mostly use it for running in the cloud.

**Comment by ric-evans** [comment]
https://github.com/icecube/skymap_scanner/blob/main/Dockerfile_no_cvmfs

**Comment by ric-evans** [comment]
Let's start with assuming CVMFS is available (and adding the constraint to `Requirements`). We can work in https://github.com/icecube/skymap_scanner/blob/main/Dockerfile_no_cvmfs?rgh-link-date=2023-02-27T21%3A57%3A29Z once this is needed. This will be phase 2 or 3 of the client starter (expect a name update to "client manager" around this point)

I'll also quote @tianluyuan (thanks for the good quotes):
>I now set
```
environment = "APPTAINERENV_I3_DATA=/cvmfs/icecube.opensciencegrid.org/data SINGULARITYENV_I3_DATA=/cvmfs/icecube.opensciencegrid.org/data I3_DATA=/cvmfs/icecube.opensciencegrid.org/data I3_TESTDATA=/cvmfs/icecube.opensciencegrid.org/data/i3-test-data-svn/trunk SKYSCAN_BROKER_AUTH=... SKYSCAN_BROKER_ADDRESS=... SKYSCAN_MQ_TIMEOUT_TO_CLIENTS=6000"
Requirements = HAS_CVMFS_icecube_opensciencegrid_org && has_avx
request_memory = 8GB
```
> in addition to the other ones
> this is with vanilla universe

**Comment by mlincett** [comment]
I guess that the following:
```
environment = "APPTAINERENV_I3_DATA=/cvmfs/icecube.opensciencegrid.org/data SINGULARITYENV_I3_DATA=/cvmfs/icecube.opensciencegrid.org/data I3_DATA=/cvmfs/icecube.opensciencegrid.org/data I3_TESTDATA=/cvmfs/icecube.opensciencegrid.org/data/i3-test-data-svn/trunk SKYSCAN_BROKER_AUTH=... SKYSCAN_BROKER_ADDRESS=... SKYSCAN_MQ_TIMEOUT_TO_CLIENTS=6000"
```
should be passed through using `getenv` rather than having them hardcoded in the client starter, right?

I am a bit confused by the three seemingly redundant specifications of `I3_DATA`, while `I3_TESTDATA` does not come with APPTAINERENV/SINGULARITYENV prefixes.

**Comment by ric-evans** [comment]
I think hardcoding is actually fine for the `*I3*` env vars. If we're assuming/requiring CVMFS access, then they shouldn't ever point elsewhere, yeah?

**Comment by ric-evans** [comment]
As for the redundancies, I'm not sure. It seems like a quirk with singularity. @tianluyuan?

**Comment by mlincett** [comment]
> As for the redundancies, I'm not sure. It seems like a quirk with singularity. @tianluyuan?

Taking a glance/grep at the reco code, it seems only `$I3_DATA` is used.

I remember we had `APPTAINERENV_` prefixes for the server env vars at some point, but now it's no longer the case so maybe the `APPTAINERENV_`/`SINGULARITYENV_` prefixes are now deprecated. Will test this.

**Comment by ric-evans** [comment]
Looking at slack thread, it looks like those prefixes are used to override what's set in the Dockerfile. And that's needed because condor overrides some env vars when/before the singularity container is executed. Or something along those lines

**Comment by mlincett** [comment]
I see how this is relevant for the client, then. Alright, I'll follow this up on PR #134 .

**Comment by tianluyuan** [comment]
I didn't set it for `I3_TESTDATA` as the container doesn't override that environment variable I don't think. i.e. `singularity run path/to/skymap-scanner` drops you in a shell with `I3_DATA` set to to local directory, but not `I3_TESTDATA.

I agree we could exclusively use them if we wanted and maybe reduce confusion.. just more typing I guess 😆

**Comment by mlincett** [comment]
Should we tentatively close this issue after #134 ?

**Comment by tianluyuan** [comment]
I think it's good for me. What is the plan for releasing the cvmfs-less images?

**Comment by ric-evans** [comment]
I'm good with closing it. We'll need cvmfs-less images eventually, but I think that should be driven by use cases
