### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#14]
Some parameters that are currently hardcoded should be probably moved to a configuration file. Do we agree to this?

What is the fashionable config file format nowadays? YAML, TOML or other?

**Comment by dsschult** [comment]
Are they constants, or config parameters like slack tokens? I'm guessing the latter.

Env variables are very popular with containers, but if you absolutely know you won't be using a container, then any of those config formats are fine.  Generally it depends on how complex your config is, and if it's only a few variables you can get by with the [Python configparser](https://docs.python.org/3/library/configparser.html).

I've also seen projects that will take both a config file and env variables, if you want to be fancy.

**Comment by mlincett** [comment]
I will try to collect some info and see what could be better tracked in a conf while not being covered by current parser arguments.

The `config.py` route is quite straightforward but in general I prefer to keep open the possibility of having multiple presets. However, no strong opinion on this from my side.

**Comment by mlincett** [comment]
A `config_listener.py` has been added for variables related to `v2_alert_listener.py` with [fa0ef39](https://github.com/icecube/skymap_scanner/pull/18/commits/fa0ef39154733ac1d327c87e8789f911c4f70a87).

Note that another (partially deprecated) `config.py` file exists under `python`, but in order to make effective any modification to its content one has to rebuild the metaproject (from which the config is actually imported).

**Comment by mlincett** [comment]
Things that (may) need to be configured:

- number of nodes to use (?)
- slack ids of the shifters to be alerted with direct mentions (critical warnings only)
- `gfu_prescale`: a subset of all GFU events (one every n-th with `n=gfu_prescale`) can be used as a heartbeat. Such events should be pre-processed (TBD to what extent) but not scanned.

**Comment by ric-evans** [comment]
> * number of nodes to use (?)

We haven't decided to make this a fixed number (even within a single event scan) ...I think that's a cool part of the MQ design :smile: it can grow dynamically and the alert listener wouldn't need to know how many there are, anyways this is going out of scope...

**Comment by mlincett** [comment]
I think this issue has long been superseded. Closing.
