### ISSUE TITLE
Incomplete scans should be flagged as such

### ISSUE THREAD

**Issue by tianluyuan** [icecube/skymap_scanner#179]
Using 3.8.2, I noticed some scans of the same event did not closely agree with scans using previous versions. It turned out the scans were incomplete but saved to disk. See below for an example.

<img width="688" alt="Screenshot 2023-04-23 at 14 06 53" src="https://user-images.githubusercontent.com/5412915/233859867-3f11e7e0-1634-4ec8-a6b1-6673215d7017.png">

I think the issue occurs [here](https://github.com/icecube/skymap_scanner/blob/ec3a2c09791884025b0c8736a208d54d16eb0fa9/skymap_scanner/server/start_scan.py#L484), where `_serve_and_collect` can return even when the scan is incomplete. Looking at the state of the output files though there is no flag that marks it as any different from completed scans. We could add a flag to the metadata to indicate this.

**Comment by ric-evans** [comment]
Incomplete scans are marked by the SkyDriver DB. But this could also by placed in the `np.array` metadata of the `SkyScanResult`

**Comment by ric-evans** [comment]
> I think the issue occurs [here](https://github.com/icecube/skymap_scanner/blob/ec3a2c09791884025b0c8736a208d54d16eb0fa9/skymap_scanner/server/start_scan.py#L484), where _serve_and_collect can return even when the scan is incomplete.

**Comment by tianluyuan** [comment]
> > I think the issue occurs [here](https://github.com/icecube/skymap_scanner/blob/ec3a2c09791884025b0c8736a208d54d16eb0fa9/skymap_scanner/server/start_scan.py#L484), where _serve_and_collect can return even when the scan is incomplete.
> 
> Should this raise an Exception instead?

I just saw this. I guess I'm not so sure how skydriver would obtain the last, partially completed scan if this raises an exception?

I think as long as we can preserve the information of all the collected pixels, and whether the scan was fully completed or partially completed then that would be probably the best-case scenario in such instances.

**Comment by ric-evans** [comment]
I see, this might actually be a bug -- the scan is marked as complete (by skydriver) on the final report even though https://github.com/icecube/skymap_scanner/blob/ec3a2c09791884025b0c8736a208d54d16eb0fa9/skymap_scanner/server/start_scan.py#L484 may have happened. I'll need to look into this further. 

As for adding a flag to the result metadata, that's a good idea. It won't hurt to have this info in two places
