### ISSUE TITLE
IceTray project or python package

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#19]
Following up on issue #13 and the discussion on Slack, a decision should be made about whether maintaining the `skymap_scanner` as a python package or as an IceTray project. In the second case, it could be integrated into `realtime_tools`.

@dsschult suggested to split the project between a pure-python _server_ side an IceTray _client_ handling the actual LLH scan. This could simplify the implementation of CI testing.

I am opening this issue for further discussion.

**Comment by ric-evans** [comment]
I strongly advocate separating `skymap_sanner` as its own python package. I've run into the scenario @dsschult mentioned about CI testing. It's much simpler adding icetray (`icecube`) as a resource, then building it with `skymap_scanner` included as a project.

**Comment by ric-evans** [comment]
CI testing is our best bet at measuring how this all will function once it's cloud-bound / in other strange new places

**Comment by ric-evans** [comment]
Also, `cloud_tools` did exactly this. They use `skymap_scanner`-type imports (technically `pulsar_icetray`), not `icecube.skymap_scanner` imports

**Comment by kjmeagher** [comment]
I think making this a python package is a good idea as well. There seems to be a general trend of people preferring code which is independent of IceTray and this code seems to be only loosely coupled with IceTray
