### ISSUE TITLE
Output of `client/reco_icetray.py` is not logged in CI

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#193]
Currently, the `client.py` calls `reco_icetray.py` passing a shell command to EWMS-pilot wrapper functions.

For some reason, this prevents the log of the `reco_icetray.py` script to appear in the CI testing output, except for the single-pixel tests where we call `reco_icetray.py` directly.

This makes developing a new reco algo a bit complicate because at first one does not have the test data for the single-pixel test.

Is there a way to recover/dump the log of `reco_icetray.py` when called through `client.py`?

**Comment by ric-evans** [comment]
Yes, this is due to an update with `ewms-pilot`. To accomplish what you want, I suggest dumping (`cat`) the `stderrfile` and `stdoutfile` files that are in the debug directory. Real-time streaming became an issue with the pilot, so it was removed.

For CI: To get the streaming effect you want, you could run a background process that `cat`s the files in a loop

**Comment by mlincett** [comment]
Thanks for the feedback @ric-evans . Just a clarification: this also means that when running the scanner manually that part of client log is lost, unless one activates the debug directory for `ewms-pilot`?

**Comment by ric-evans** [comment]
> Thanks for the feedback @ric-evans . Just a clarification: this also means that when running the scanner manually that part of client log is lost, unless one activates the debug directory for `ewms-pilot`?

That's right. By default, each reco's stderr & stdout are not visible.

**Comment by mlincett** [comment]
> > Thanks for the feedback @ric-evans . Just a clarification: this also means that when running the scanner manually that part of client log is lost, unless one activates the debug directory for `ewms-pilot`?
> 
> That's right. By default, each reco's stderr & stdout are not visible.

OK, I am still figuring out how everything works, so I'll just drop a few notes:

1.  [Documentation](https://htcondor.readthedocs.io/en/latest/users-manual/file-transfer.html) says that "HTCondor detects any newly-created files at the top level of this sandbox directory, and transfers them back to the submitting machine". I seem to get files and _empty_ directories, maybe this is by design.
2. It seems that is possible to declare which files / directories are to be "transferred out", and that includes the directory content.
3. It could be nice to have `ewms-pilot` to build a directory tree under the debug directory, separating logs from working files. This way we can choose what to transfer back by tuning the HTCondor submit file (avoid the current "all or nothing" situation).
4. It seems to me that after recent `ewms-pilot` modifications the jobs no loger exit and remain hanging in "run" state on Condor. Before, most of them were actually finishing.

No urgent actions are needed though. For now I can debug by ssh-ing into condor jobs. We should discuss a better long-term plan when you are back, @ric-evans .

**Comment by mlincett** [comment]
I think we can have two solutions:
1. for CI, create an helper script that walks over the content of the client debug directory and dumps the log of the first pixel reco stdout/stderr. Not sure if it easy to run the script even when the reco fails.
2. for manual scans, add a debug option to `client_starter` that (1) enables the EWMS-pilot debug dir and (2) explicitly ask to condor to transfer it back.

I think however that (1) may become unnecessary because with (2) it becomes very straightforward to create the single-pixel CI test.

**Comment by ric-evans** [comment]
#199 accomplishes this now. Example:
