### ISSUE TITLE
Deploy Pulsar Servers on PRP

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#20]
After https://github.com/icecube/skymap_scanner/issues/2.

@briedel has deployed a pulsar cluster on PRP (Pacific Research Platform), a distributed K8S cluster in CA. It is earlier to scale than other clusters.

**Comment by dsschult** [comment]
Note that Pulsar is already deployed, but you'll probably need to handle setup/teardown of the queue to use for each scan.
