### ISSUE TITLE
Change name of input pulse series

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#240]
The new pole data format replaces `SplitUncleanedInIcePulses` with `SplitInIcePulses`. The former is still somewhat hardcoded in Skymap Scanner.

It is VERY URGENT to support this because we may be soon left without a working scanner for the incoming alerts.

**Comment by G-Sommani** [comment]
If we want it to be compatible with the alerts from the past we should implement it in a way that can look in an i3 file for both `SplitUncleanedInIcePulses` and `SplitInIcePulses`, right?

**Comment by mlincett** [comment]
Yes, but this fallback logic needs be implemented individually in each reco module because they all read from `cfg.INPUT_PULSES_NAME`.

The fastest option for a temporary solution is replacing this:
```
build/lib/skymap_scanner/config.py:INPUT_PULSES_NAME: Final = "SplitUncleanedInIcePulses"
```
and have a tag of the scanner ready to run on a new alert if it comes.

**Comment by G-Sommani** [comment]
I created the branch `pulse-tag-new-filters` with that modification

**Comment by tianluyuan** [comment]
I think changing it in `config.py` with a major version update could work.

Do we know how it behaves for replayed past alerts? It might be that with the new realtime software replayed old alerts will have `SplitInIcePulses`, in which case this replacement could be the solution.

**Comment by mlincett** [comment]
> I think changing it in `config.py` with a major version update could work.
> 
> Do we know how it behaves for replayed past alerts? It might be that with the new realtime software replayed old alerts will have `SplitInIcePulses`, in which case this replacement could be the solution.

The pulse series name is frozen in the IceTray serialized data blob part of the JSON, so this will not be backwards compatible.

It should be possible on the other hand to map the realtime data "version" string (that it's in the input JSON) to the appropriate pulse series name, instead of having it fixed.

**Comment by blaufuss** [comment]
after decoding the json blob, could have a conditional rename of the frame object.
