### ISSUE TITLE
Config of GCD path(s)

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#25]
Going through duplicate and divergent files (#5), here's a summary on how the path of GCD files is configured in `conf.py`:

`cloud_tools` uses a variable named `base_GCD_path`, in turns loaded in:
* `cloud_tools/calculate_online_alert_dict.py`
* `cloud_tools/extract_i3_file.py`
* `cloud_tools/prepare_frames.py`
* `cloud_tools/save_pixels.py`
* `cloud_tools/scan_pixel.py`

`skymap_scanner/python` uses a variable (list) named `GCD_base_dirs`, which is loaded in:
* `python/extract_json_message.py`
* `python/load_scan_state.py`
* `python/perform_scan.py`
* `python/utils.py` (`cloud_tools/utils.py`)
* `test-case-scan/extract_json_message_mod.py`
* `test-case-scan/perform_scan.py`

**Comment by ric-evans** [comment]
Thank you @mlincett! This is very helpful
