### ISSUE TITLE
Update baseline GCDs

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#252]
With 2023 run start we need to update the baseline GCDs. Baseline GCDs are fetched from `convey` in the generation of the base IceTray container. Hence the base IceTray container should be updated (*).

There seems to be no easy way for a Skymap Scanner developer to see:
- whether a new IceTray container has been produced;
- whether such container includes the required GCD (at least without trying to run the code once).

**Can we rebase Skymap Scanner on a newer IceTray including the latest GCD?**

(*) this workflow is far from optimal because the container content is determined by _when_ the container is generated rather than by the `Dockerfile` content.

Please note that as I have already observed in https://github.com/icecube/realtime/issues/8 a quick solution would be to mirror the baseline GCDs to `prod-exe`.

**Comment by dsschult** [comment]
Would it be better to stop doing the baseline GCDs in the icetray image and do them in the scanner image instead?

We've had this PR lingering for a while: https://github.com/WIPACrepo/docker-icecube-icetray/pull/10

**Comment by mlincett** [comment]
> Would it be better to stop doing the baseline GCDs in the icetray image and do them in the scanner image instead?
> 
> We've had this PR lingering for a while: [WIPACrepo/docker-icecube-icetray#10](https://github.com/WIPACrepo/docker-icecube-icetray/pull/10)

This could indeed be the best option.

**Comment by dsschult** [comment]
@mlincett ok, I've merged that upstream PR.  Could you change the skymap scanner Dockerfiles to grab the baseline GCDs from http://prod-exe.icecube.wisc.edu/baseline_gcds/ ?

**Comment by ric-evans** [comment]
This will be versioned along with the image, so I'm good with any needed changes. I'd only be concerned if we're grabbing the data at runtime without any versioning, like checksums (see https://github.com/icecube/skymap_scanner/issues/166)
