### ISSUE TITLE
Divergent versions of `extract_json_message.py`

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#26]
The file `extract_json_message.py` is divergent between `python` and `cloud_tools`, so I am trying to summarise the functionalities.

The file mainly provides the `extract_json_message()` method, that in turn recalls `full_event_followup.i3live_json_to_frame_packet()`.

The version in `cloud_tools`: 
- calls `full_event_followup.i3live_json_to_frame_packet()`
- checks that the 4th entry in the frame packet is a DAQ (Q) frame
- reverts the name of `QI3EventHeader` to `I3EventHeader` (if applicable)
- simply returns the frame packet.

The version in `python`:
- checks if the cache dir is valid
- calls `full_event_followup.i3live_json_to_frame_packet()`
- parses the state packet into a `event_id` and a `state_dict` with the function `__extract_frame_packet()`.
- returns `load_scan_state()` against `event_id` and `state_dict`.

Coming to the auxiliary function `__extract_frame_packet()`:
- checks that length of frame packet = 5
- checks that last frame in frame packet is a physics (P) frame
- _move the last packet frame from Physics to the Physics stream_ by calling `rewrite_frame_stop()` (??)
- creates `event_id_string` from physics frame header
- handles / creates the individual event cache under the general cache dir
- lot of complicate handling of GCD / GCD diff file (to be further investigated)
- calls `prepare_frames()` that apparently returns (modified?) the `frame_packet` and an `Excluded_DOMs` object.

Clearly the divergence reflects different requirements between the two modes (realtime and offline), and it seems there is room for better code organisation and documentation.

**Comment by mlincett** [comment]
> One thing I feel is missing is a high level overview of what information is needed and what the message should contain for the scan to work.

If I understand correctly, in this context the _message_ is just a JSON dictionary carrying I3 frames in binary format (see [example](https://convey.icecube.wisc.edu/data/user/ckopper/event_HESE_2017-11-28.json)).

I am not aware of how this can be baked from an I3 file.

**Comment by ric-evans** [comment]
Note: https://github.com/icecube/skymap_scanner/blob/master/skymap_scanner/extract_json_message.py was copied from https://github.com/icecube/skymap_scanner/blob/master/python/extract_json_message.py

**Comment by mlincett** [comment]
Code has been largely reorganised so this is no longer an "issue".
