### ISSUE TITLE
Divergent versions of `perform_scan.py`

### ISSUE THREAD

**Issue by mlincett** [icecube/skymap_scanner#27]
The `perform_scan.py` differs between `cloud_tools` and `python` (see #5).

The `cloud_tools` version is designed to operate with a fixed NSIDE value, while the `python` version has the machinery to perform the hierarchical scan as we do in real time.

The core functionality is provided as an IceTray module named `SendPixelsToScan`.

The input is prepared by `extract_json_message()` (see #26). For `cloud_tools`, this is simply the GCDQp frame packet. For `python`, the `state_dict` is loaded.

The version in `cloud_tools` has added reco functionality (see `get_reco_losses_inside()`). This part could be easily merged.

**Comment by mlincett** [comment]
The `CreatePFrame()` function, however, presents an odd difference:
- `dec = dec - numpy.pi/2.` in `python`
- `dec = numpy.pi/2. - dec` in `cloud_tools`

The declination value is fed to calculate zenith and azimuth, I have no idea why the `dec` sign is reversed between the two versions.

**Comment by ric-evans** [comment]
@mlincett is this still an issue since we're going with the `python/` implementation?
