### ISSUE TITLE
Store reconstruction files as runRUNNUMBER.evtEVENTNUMBER.EVENTTYPE

### ISSUE THREAD

**Issue by clagunas** [icecube/skymap_scanner#33]
As of now the outcome files (the reconstruction i3 files and the plots) are always saved as runXXX.evtYYY.**HESE**, regardless of the event type. Some scripts fail if the name of the event is not written like that. It would be better to use the proper event type for each alert, either GFU/HESE/EHE or Bronze/Gold

**Comment by mlincett** [comment]
Good point. I noticed this. The filename can be derived from `event['value']['data']['unique_id']`. For the label, some logic is required to determine which is the top-priority selection. Ideally all this is done in a `RealtimeEvent` wrapper class where all these notions are centralised.

**Comment by ric-evans** [comment]
fixed by #112
