### ISSUE TITLE
Remove Deprecated Code

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#36]
Any files that need to persist should be moved to `skymap_scanner/` or its own directory with a descriptive name. This is also a good time to remove any dead legacy code. One option is to run multiple test runs with a coverage tool.

**Comment by kjmeagher** [comment]
that `CMakeLists.txt` doesn't need to be there either

**Comment by ric-evans** [comment]
#63 is a quick fix until we unanimously decide the remove the old stuff

**Comment by mlincett** [comment]
Quoting myself from #63: I have provided at [skymap-scanner-legacy](https://github.com/icecube/skymap-scanner-legacy) a minimal interface to the SVN version in CVMFS, and produced a tag v1.5 of this repo that can be used to track back the old codes. I think there is no more reason to keep deprecated_files in the main branch.
