### ISSUE TITLE
Integrating Slack into Script-Based Server

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#37]
@mlincett I've largely preserved the reporting and logging callbacks, see `ProgressReporter`. We will need to decide on a design for how to "pass in" the callback functions. This will ultimately depend on how we execute the scanner. The scanner is started as an importable module in the (pre-existing) alert listener (2.0). I don't think this is scalable. Instead, I'd prefer to fire off a subprocess script that will start up the server and n clients. This way if the alert listener goes down, the server is still operational.

_Originally posted by @ric-evans in https://github.com/icecube/skymap_scanner/issues/30#issuecomment-1152773515_

**Comment by mlincett** [comment]
The new listener I have in my branch is already designed to simply spawn a subprocess in order to process an event (after some basic checks). I just need to know how to call the script / pass the event and we should be good.

**Comment by ric-evans** [comment]
Glad we agree on the subprocess-script design.

**Comment by mlincett** [comment]
> How do you want to do the callbacks? I think how it is right now may be too configurable/customizable (we can pass in _any_ function). We could move the callback code to the skymap scanner server itself. For example, pass in a slack token and send a message from the server.

I do not like that much the idea of passing generic callback functions, indeed.

I agree that logic of _what should be reported_ should be part of the `ProgressReporter`.

For Slack, I have produced a `SlackInterface` class that should be instantiated in the main and passed to any function that needs to post to Slack.

**Comment by ric-evans** [comment]
> For Slack, I have produced a `SlackInterface` class that should be instantiated in the main and passed to any function that needs to post to Slack.

Great. We can do this after #28 closes

**Comment by mlincett** [comment]
A lot has changed on since we last discussed about this.

I think we are finally moving towards a design where the skymap scanner will be deployed as a service that can be invoked through an API.

As such, there should be some way to report back the relevant logs back to the caller.

**Comment by ric-evans** [comment]
@mlincett yes, there's more to come soon about this. I'm definitely thinking about the slack functionality in the upcoming "Scanner as a Service" design

**Comment by ric-evans** [comment]
Replaced by https://github.com/icecube/skymap_scanner/issues/95
