### ISSUE TITLE
Clean up repeated files from cloud_tools/ and python/

### ISSUE THREAD

**Issue by blaufuss** [icecube/skymap_scanner#5]
There are several files that were copied to cloud_tools from old skymap_scanner that appear to be old and/or modified copies of old scripts from ancient versions of skymap_scanner from SVN.  These need a more careful look as things move forward.  I suspect some pieces of these might be needed as things transition to cloud again with modern scan.  But "standard condor" scan will be from python/ and resources/ dirs right now (as they're currently run)

Please consider these repeated files also present in python/:
- cloud_tools/
    config.py
    extract_json_message.py
    perform_scan.py
    scan_pixel.py/scan_pixel_distributed.py (and python/traysegments/scan_pixel_distributed.py)
    utils.py

Several commits from SVN history might be helpful to see what's changed in the Condor scanner since it split:
https://code.icecube.wisc.edu/projects/icecube/log/IceCube/sandbox/ckopper/skymap_scanner?rev=185232

**Comment by mlincett** [comment]
Reporting from Slack a conversation by @claudiok (I think it's good to have it here). Note: now the main directory of this repo contains what is referred to as "SVN version" so the "new" scanner in Claudio's words refers to the code now present in `cloud_tools`.

> Here’s the history: I moved the SVN one to GitHub into `icecube/skymap_scanner` (well, in my personal account at the time, but we moved that over). Then I went and made that work for the v2 alert scans to work on AWS and chose Apache Pulsar to send events, whereas the scanner in SVN continued to use the ZMQ-based queue. The actual physics/internal scan settings are the exact same for both of them, but the infrastructure has changed completely. But the icetray script setttings on the minimizer and such are the same.
> I think I also added lots of cleanup code to the `icecube/skymap_scanner` and integrated some other recos for purposes of completeness when we did the archival scans (that’s why it runs the DNN reco and includes tensorflow). The SVN version has been optimized to run on HTCondor however, at least the per-pixel processing is the same. However, in the move to a more parallel scheme, the “new” skymap scanner in `icecube/skymap_scanner` also lost some functionality: the SVN version has a heuristic on when to schedule a finer-grained scan for each rough pixel (larger nside parameter). This is something that the “new” scanner doesn’t have - for purposes of the archival scan, we did basically do “full skymaps” at low resolution and then “by hand” committed finer-grained maps. Given that we continued to run the SVN version as the production version, it has seen updates to make it usable in the actual realtime chain, which has not been done for the GitHub version. So.. there you have it, that’s why the two are completely different now when seen from the outside while their core (the millipede per-pixel reco) is the same.
