### ISSUE TITLE
Decrease Message Size

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#57]
> In testing we've used two types of messages (incoming and outgoing). The first ranges ~100kB to ~700kB. The second, ~20kB-120kB. [...] we may be able to get the messages down to ~100kB and ~1kB, respectively.

#### Current Design
- to-client message (1-per-pixel) = geometry frames + gcd strings + the pixel's frame
   * ~100kB to ~700kB
- to-server message (1-per-pixel) = whole pixel's frame w/ added reco info
   * ~20kB-120kB

#### Proposed Design
- "startup" data (1-per-client) = geometry frames + gcd strings
   * ~100kB to ~700kB
   * a pkl file provided via command-line args
   		- we'll need to change the start-up pattern so we can grab the pkl from the active server (similar to #50)
- to-client message (1-per-pixel) = the pixel's frame
   * ~100kB
- to-server message (1-per-pixel) = a few ids , llh, recoLossesInside, and recoLossesTotal
   * ~1kB
   * this means no longer saving i3 files for each pixel
   * need @mlincett's input (do we need to be saving i3 files?)

**Comment by mlincett** [comment]
I think there is no need to keep one `i3` file per pixel. If it turns out we are leaving out useful information from the client's report we can always expand the messages in the future.
