### ISSUE TITLE
Get Relative Tolerances for Pixel Datapoints from Production

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#60]
Let's run the production scanner at least twice and see how the `npz` results differ pixel-to-pixel. 

Then, for `ScanResult.is_close()`, we can decide whether to disqualify pixels with zero-energies (we're currently doing this) or to increase the `rtol`.

**Comment by mlincett** [comment]
PR #62 was meant to add alternative test data, namely the result of a second scanner iteration using the version of the scanner currently deployed in realtime.

Checking the differences between the two iterations (reference and alternative), it seems the `llh` values always match, while there are differences in the reconstructed reco losses across the scanned pixels.

The RMS of the relative difference, defined as `(ref - alt) / ref`, can be as large as `0.05`. Not sure this is the best metric.

Note that we do not use the reconstructed losses for anything right now, but we should try to pinpoint the origin of any non-deterministic behaviour.

**Comment by ric-evans** [comment]
There are other issues (https://github.com/icecube/skymap_scanner/issues/200 and https://github.com/icecube/skymap_scanner/issues/242) that are more relevant. Closing this issue.
