### ISSUE TITLE
Configurable N-Side Refinement Iterations

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#79]
@tianluyuan pointed out that the n-side iterations (refinements) are somewhat hardcoded currently (there's only a configurable min and max). A user-specified list would allow us to optimize this as needed, based on measurements we see in a production environment.

**Comment by ric-evans** [comment]
https://github.com/icecube/skymap_scanner/pull/109 replaces `--max-nside` and `--min-nside` with a single `--nsides [min [max]]`. This also allows, defining a single nside value.

This is the first step toward closing this issue.

**Comment by mlincett** [comment]
> #109 replaces `--max-nside` and `--min-nside` with a single `--nsides [min [max]]`. This also allows, defining a single nside value.
> 
> This is the first step toward closing this issue.

Thank you Ric! We should however define a way to limit the sky region for the scan with `nside=min`. Right now, my understanding is that `min-nside` is always an all-sky scan.

**Comment by ric-evans** [comment]
> > #109 replaces `--max-nside` and `--min-nside` with a single `--nsides [min [max]]`. This also allows, defining a single nside value.
> > This is the first step toward closing this issue.
> 
> Thank you Ric! We should however define a way to limit the sky region for the scan with `nside=min`. Right now, my understanding is that `min-nside` is always an all-sky scan.

Sure. I'll have to rely on you or @tianluyuan to do that part :smile: SkyDriver will use a list of nside values, so from a systems perspective we'll be ready for the next steps

**Comment by ric-evans** [comment]
Update: `--nsides` will now include pairings of the nside value and its pixel extension: `--nsides [min:pixext [max:pixext]]`

The goal:
```

Still a first step. I haven't touched anything beyond the argparse logic

**Comment by ric-evans** [comment]
Note to self:
