### ISSUE TITLE
Investigate migration of skymap_scanner to new reconsrtuction algorithsm under the hood,

### ISSUE THREAD

**Issue by blaufuss** [icecube/skymap_scanner#8]
There are many reasons to think that the current millipede scan isn't perfect. We should investigate options
for:
* migrating to @nwhitehorn's new double precision millipede implementation in icetray/main
* SplineMPE scan might be a better idea.

Work with experts in the reco/systematics working group for suggestions and input.

**Comment by mlincett** [comment]
- Re: migrating to millipede double precision, we can discuss this in the upcoming call/workshop. However, validation is an issue so we should agree on a sample of events that is sustainable to rescan in order to check agreement / improvement.
- Re: where to go in the future, I expect the discussion will take a while, however we can start restructuring the code so to make it modular / configurable at runtime, rather than having fixed hardcoded setups.

**Comment by briedel** [comment]
Couple thoughts here:

Short-term: Change to splines/tables @tianluyuan suggested
Medium-term: See if we can get a track model of @mhuen cascade generator reco, so we have a fast reco with poorly constraint error that we can use to constrain the scan
Long-term: Somehow get a generator model to replace millipede

**Comment by dsschult** [comment]
> * Re: where to go in the future, I expect the discussion will take a while, however we can start restructuring the code so to make it modular / configurable at runtime, rather than having fixed hardcoded setups.

Note that part of Ric's queue work will likely separate out the "client" part of the scan into an independent script.  That should make it easy to swap between algorithms.

**Comment by ric-evans** [comment]
> > * Re: where to go in the future, I expect the discussion will take a while, however we can start restructuring the code so to make it modular / configurable at runtime, rather than having fixed hardcoded setups.
> 
> Note that part of Ric's queue work will likely separate out the "client" part of the scan into an independent script. That should make it easy to swap between algorithms.

Coming back to this: yes, this is relatively simple. 

On the app-server end, the only apparent assumption needing to change is relying on the `"MillipedeStarting2ndPass_millipedellh"` key for the llh value. On the client-side, we would swap the tray segments/modules for a non-millipede reco--easy. We'd also need to signal which reco we'd want to use (eg: add another attribute to the MQ payload)

**Comment by ric-evans** [comment]
From a Slack thread with @mjlarson:

**Comment by ric-evans** [comment]
Once #59 is merged, the reconstruction algorithm is configurable by the `--reco-algo` command-line argument. There's just the one option, millipede, but it looks more probable now that we'll (@mlincett) be able to swap algorithms at runtime (https://github.com/icecube/skymap_scanner/issues/8#issuecomment-1031349939) in the future.

**Comment by ric-evans** [comment]
From a Slack thread with @mjlarson:
```
    tray.Add(spline_reco.SplineMPE, "SplineMPE_l4",
	        fitname="SplineMPE_l4",
	        configuration="max",
	        PulsesName = "TWSRTHVInIcePulses",
	        TrackSeedList = ["SplineMPE"],
	        BareMuTimingSpline = infmuonprobsplinepath,
	        BareMuAmplitudeSpline = infmuonampsplinepath,
	        StochTimingSpline = stochprobsplinepath,
	        StochAmplitudeSpline = stochampsplinepath,
	        EnergyEstimators = ["SplineMPEMuEXDifferential"])
```
> with
```
infmuonampsplinepath = "/cvmfs/icecube.opensciencegrid.org/data/photon-tables/splines/InfBareMu_mie_abs_z20a10_V2.fits"

infmuonprobsplinepath = "/cvmfs/icecube.opensciencegrid.org/data/photon-tables/splines/InfBareMu_mie_prob_z20a10_V2.fits"

stochampsplinepath = "/cvmfs/icecube.opensciencegrid.org/data/photon-tables/splines/InfHighEStoch_mie_abs_z20a10.fits"

stochprobsplinepath = "/cvmfs/icecube.opensciencegrid.org/data/photon-tables/splines/InfHighEStoch_mie_prob_z20a10.fits"
```

We'll also need to know the outputted keys for the `I3Frame` instance.

**Comment by ric-evans** [comment]
https://github.com/icecube/skymap_scanner/pull/69#issuecomment-1297442070
