### ISSUE TITLE
Iterations not fully asynchronous

### ISSUE THREAD

**Issue by tianluyuan** [icecube/skymap_scanner#84]
The current handling of each iteration isn’t fully asynchronous, as the skymap_scanner waits for the previous nside to complete before starting the next one. The existing followup scanner bot will start up the next iteration once 30% have been scanned, which probably gives a nice speed up as some pixels can take much longer than others.

Related to #79

**Comment by ric-evans** [comment]
After a conversation with @tianluyuan, @dsschult, and @briedel, we've decided to enable this for realtime via some kind of flag, disabled by default. Perhaps this can be a variable with the predictive percentage (currently 30%)

The tradeoff discussed is:

**Comment by ric-evans** [comment]
Historical event scanning is 1000 bicycle commuters. Realtime event scanning is a Ferrari

**Comment by ric-evans** [comment]
With predictive scanning, nondeterministic scanning is introduced. The practical results are not affected, but re-scans may not result in the same exact skymap, as different regions (local minima) may have been refined before finding the global minimum.
