### ISSUE TITLE
Scanner bot has to wait until all messages are sent before collecting

### ISSUE THREAD

**Issue by tianluyuan** [icecube/skymap_scanner#85]
Currently in `start_scan.py` all messages need to be [sent](https://github.com/icecube/skymap_scanner/blob/master/skymap_scanner/server/start_scan.py#L758) before collection can occur. This can sometimes cause additional wait time, for example when 3k pixel/variation combinations are sent.

**Comment by ric-evans** [comment]
I believe this wait time we attributed to a temporary slowdown in the broker. This would only be a problem if T(sending) > T(single reco). I don't think this is normally the case.

I'd happily re-open/discuss this further if we see it happen consistently in production. I believe efforts ought to be put on #84 first.
