### ISSUE TITLE
Checkpoint or cache progress in case of server failure

### ISSUE THREAD

**Issue by tianluyuan** [icecube/skymap_scanner#92]
Currently if the server dies the scan has to be restarted from scratch. It might be worth periodically saving the `nsides_dict` in the cache directory and picking up from there. Though one would need to be careful and only do so when identical settings are used.

**Comment by dsschult** [comment]
I think we're leaving it up to SkyDriver to properly handle server failure.  I know @ric-evans and I discussed this, not sure if we decided it was rare enough to fully restart, or if we wanted to save progress in the DB.

**Comment by ric-evans** [comment]
> Though one would need to be careful and only do so when identical settings are used.

**Comment by ric-evans** [comment]
> Though one would need to be careful and only do so when identical settings are used.
This is a red flag to me. I see a lot of complexities that could make this very difficult to get right. I understand wanting to recoup some processing time, but I think our time would be better spent speeding up the sending of pixels to clients.

Honeslty, I'd rather have SkyDriver restart the entire scan. If we're seeing enough server failures where this affects aggregate event statistics, we have a much larger problem on our hands.

**Comment by tianluyuan** [comment]
That makes sense. I've been able to workaround some of this with the faster reco setting as well. Closing for now.
