### ISSUE TITLE
Send Progress Reports & Results to SkyDriver REST API

### ISSUE THREAD

**Issue by ric-evans** [icecube/skymap_scanner#95]
After https://github.com/WIPACrepo/SkyDriver/issues/1, use SkyDriver's REST API to:
- send progress reports (which can eventually be forwarded to a 3rd party slack-posting script)
- send final results
   * we'll need to settle on a format for this, npz or json?

Removes/replaces all the "slack" logic in the scanner server. 

This method is more flexible--data will be persisted by SkyDriver's DB, and third parties can retrieve on a pull (GET). This opens possibilities for non-slack purposes 

Replaces https://github.com/icecube/skymap_scanner/issues/37

**Comment by mlincett** [comment]
So the REST API would act as a front-end to the database, which is not exposed to the user, right?

I think JSON makes perfect sense for transmitting the results and I see no benefit in a rigid binary format.

**Comment by ric-evans** [comment]
That's right.

I agree. `ScanResult` will need to be transformed to use JSON--not sure how far we want to go. Also, not sure if we want to support npz going forward. @tianluyuan do you have any ideas on this?

**Comment by tianluyuan** [comment]
It would be nice if we can preserve the existing support for loading in npz in `ScanResult`, since all of the results I've processed are currently stored in that format. At least for awhile longer. Going forward it's fine with me if the default format changes to json.

**Comment by ric-evans** [comment]
@tianluyuan would a converter script be enough for your purposes? That way we can make the breaking change, but you can still keep your results, albeit with one more step.

**Comment by ric-evans** [comment]
Also, is the JSON number (double) type suitable for the data points stored in the current format?

**Comment by tianluyuan** [comment]
That should work, I added a header array that has all the metadata which should be preserved. Double should be fine too, i think all the numpy arrays default to that. It would be interesting to get a file size comparison.

Here's an example file that I've been working with `~tyuan/test/scan/test5/out/run00000000.evt000000000000.HESE_8_64_512.npz`.

**Comment by mlincett** [comment]
As a part of this, I suggest taking a look at:
https://github.com/icecube/skymap_scanner/blob/d11cd430da1cec6db344965b84dc4d943c8bdf17/skymap_scanner/config.py#L68-L82

- `SKYSCAN_SLACK_*` variables can probably be removed; 
- `SKYSCAN_*_INTERVAL_SEC` variables are possibly still relevant for REST-based progress reporting?

**Comment by ric-evans** [comment]
@mlincett I agree. It's on my radar

**Comment by ric-evans** [comment]
By including the metadata, we're looking at 918 bytes
